name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Directory Structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Change to the appropriate JDK version

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./Online-Food-Order/pom.xml  # Update this path if your pom.xml is in a subdirectory

    - name: Run tests
      run: mvn test
      working-directory: ./Online-Food-Order/pom.xml  # Update this path if needed

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./Online-Food-Order/pom.xml # Update this path if your pom.xml is in a subdirectory

   
