name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Directory Structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Set to the appropriate JDK version

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./Online-Food-Order # Update this path to your project directory

    - name: Run tests
      run: mvn test
      working-directory: ./Online-Food-Order # Update this path to your project directory

    - name: Package with Maven
      run: mvn package
      working-directory: ./Online-Food-Order # Update this path to your project directory
